# Generated by Django 5.2.6 on 2025-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_marca_alter_producto_iva_alter_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
