# Generated by Django 5.2.6 on 2025-10-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ancho_material', models.DecimalField(decimal_places=2, help_text='Ancho en cm', max_digits=10)),
                ('alto_material', models.DecimalField(decimal_places=2, help_text='Alto en cm', max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Costo total de la lámina o rollo', max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de ganancia', max_digits=5)),
                ('costo_cm2', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('precio_cm2', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_especiales', to='productos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_especiales', to='productos.marca')),
            ],
        ),
    ]
