# Generated by Django 5.2.6 on 2025-10-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoservicio',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='productoservicio',
            name='precio_venta',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca'),
        ),
        migrations.AlterField(
            model_name='productoespecial',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_especiales', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='productoespecial',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_especiales', to='productos.marca'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_servicio', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_servicio', to='productos.marca'),
        ),
    ]
