# Generated by Django 5.2.6 on 2025-10-02 15:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productoespecial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_corte', models.DecimalField(decimal_places=2, help_text='Ancho del corte en cm', max_digits=10)),
                ('alto_corte', models.DecimalField(decimal_places=2, help_text='Alto del corte en cm', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('descuento_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('producto_especial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_especial', to='productos.productoespecial')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_especiales', to='ventas.venta')),
            ],
        ),
    ]
