# Generated by Django 5.2.6 on 2025-10-02 16:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoservicio'),
        ('ventas', '0002_detalleventaespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_servicio', to='productos.productoservicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='ventas.venta')),
            ],
        ),
    ]
