# Generated by Django 5.2.6 on 2025-10-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturacompra',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta (opcional)', max_digits=20, null=True),
        ),
    ]
